{% set name = "booklet" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/booklet-{{ version }}.tar.gz
  sha256: 3729a2055ef824be3a02965c91889fded08b0b5ce1894592e3374cc4df036bab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - hatchling
  run:
    - python >=3.8
    - portalocker

test:
  imports:
    - booklet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mullenkamp/booklet
  summary: A python key-value file database
  description: A python key-value file database
  doc_url: https://github.com/mullenkamp/booklet
  dev_url: ''
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mullenkamp
